language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t vincentwong/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vincentwong/react-test yarn test

after_success:
  - docker build -t vincentwong/multi-client ./client
  - docker build -t vincentwong/multi-nginx ./nginx
  - docker build -t vincentwong/multi-server ./server
  - docker build -t vincentwong/multi-worker ./worker
  # Login to docker CLI
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Take those images and push them to docker hub
  - docker push vincentwong/multi-client
  - docker push vincentwong/multi-nginx
  - docker push vincentwong/multi-server
  - docker push vincentwong/multi-worker
